apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: inzynierka
  labels:
    app: web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: michaldocker123/inzynierka-web:0.2
          ports:
            - containerPort: 8080
          env:
            - name: mysql-host
              valueFrom:
                secretKeyRef:
                  name: mysql-host
                  key: mysql-host
            - name: mysql-password
              valueFrom:
                secretKeyRef:
                  name: mysql-password
                  key: mysql-password
            - name: mysql-port
              valueFrom:
                secretKeyRef:
                  name: mysql-port
                  key: mysql-port
            - name: mysql-user
              valueFrom:
                secretKeyRef:
                  name: mysql-user
                  key: mysql-user
            - name: FLASK_ENV
              value: k8s
            - name: FLASK-SECRET-KEY
              valueFrom:
                secretKeyRef:
                  name: flask-secret-key
                  key: flask-secret-key
            - name: GMAIL-USER
              valueFrom:
                secretKeyRef:
                  name: gmail-user
                  key: gmail-user
            - name: GMAIL-PASS
              valueFrom:
                secretKeyRef:
                  name: gmail-pass
                  key: gmail-pass
            - name: JWT-SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: jwt-secret
            - name: PEPPER
              valueFrom:
                secretKeyRef:
                  name: pepper
                  key: pepper
            - name: AES-KEY
              valueFrom:
                secretKeyRef:
                  name: aes-key
                  key: aes-key
